version: "3.8"

services:
  db:
    build:
      context: "./db"
    container_name: db
  backend:
    build:
      context: "./backend"
    container_name: backend
  frontend:
    build:
      context: "./frontend"
    container_name: frontend
