FROM maven:3.9.3-openjdk-21 AS build

WORKDIR /app

COPY . .


RUN mvn clean package -DskipTests



FROM eclipse-temurin:21-jdk

WORKDIR /app


COPY --from=build /app/target/tutorials-0.0.1-SNAPSHOT.jar /app/tutorials-0.0.1-SNAPSHOT.jar



COPY scripts/wait-for-it.sh /usr/local/bin/wait-for-it.sh
RUN chmod +x /usr/local/bin/wait-for-it.sh


EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/wait-for-it.sh","db:5432","--","java", "-jar", "/app/tutorials-0.0.1-SNAPSHOT.jar"]