FROM ubuntu:22.04


RUN apt-get update && \
  apt-get install -y \
  wget \
  gnupg \
  software-properties-common && \
  apt-get clean

WORKDIR /app

COPY --from=build /app/target/tutorials-0.0.1-SNAPSHOT.jar /app/tutorials-0.0.1-SNAPSHOT.jar

COPY scripts/wait-for-it.sh /usr/local/bin/wait-for-it.sh
RUN chmod +x /usr/local/bin/wait-for-it.sh

EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/wait-for-it.sh", "db:5432", "--", "java", "-jar", "/app/tutorials-0.0.1-SNAPSHOT.jar"]