FROM maven:3.9.3-eclipse-temurin-21 AS build

WORKDIR /app

COPY . .


RUN mvn clean package -DskipTests



FROM eclipse-temurin:21-jdk

WORKDIR /app


COPY --from=build /app/target/tutorials-0.0.1-SNAPSHOT.jar /app/tutorials-0.0.1-SNAPSHOT.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "/app/tutorials-0.0.1-SNAPSHOT.jar"]