FROM openjdk:21-jdk-alpine

WORKDIR /app

COPY --from=build /app/target/tutorials-0.0.1-SNAPSHOT.jar /app/tutorials-0.0.1-SNAPSHOT.jar

COPY scripts/wait-for-it.sh /usr/local/bin/wait-for-it.sh
RUN chmod +x /usr/local/bin/wait-for-it.sh

EXPOSE 8080

CMD ["/usr/local/bin/wait-for-it.sh", "db:5432", "--", "java", "-jar", "/app/tutorials-0.0.1-SNAPSHOT.jar"]